### PR TITLE
Gitignored ctre_sim folder

### PR DESCRIPTION
**Pull request by Arnav814**
Gitignored ctre_sim and removed all files in it.

## Overview

Added the ctre_sim folder to the gitignore, so it doesn't show up in every commit.

### CODE REVIEW

**Comment by Ash1R** [comment]
@Arnav814 what/why is the .idea?

**Comment by Arnav814** [comment]
I think that's some Intellij thing. I didn't add that, though.

**Comment by Ash1R** [comment]
Do we need it?

**Comment by Arnav814** [comment]
I don't know. Does anyone use Intellij IDEA?
In any case, I don't think there's any harm in leaving it in.

**Comment by Ash1R** [comment]
Tyrus does. I'll leave it in for now and approve.

**Review by Ash1R — APPROVED** [review]

**Review by Kyle-Eldridge — APPROVED** [review]

**Pull request merged**
